on:
  push:
    branches-ignore:
      - "master"


jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: |
          python -m pip install check-jsonschema
      - run: |
          check-jsonschema schema/schema.json --check-metaschema